from typing import List, Dict
from enum import Enum
from dataclasses import dataclass
from .Regions import Regions, RTRegion

class LocationType(Enum):
    OkRank = 0
    SuperbRank = 1
    PerfectRank = 2

@dataclass
class RTLocation:
    name: str
    region: RTRegion
    game_id: str
    type: LocationType

location_list: List[RTLocation] = [
    RTLocation("Karate Man OK", Regions.l0, "0_o", LocationType.OkRank),
    RTLocation("Karate Man SUPERB", Regions.l0, "0_s", LocationType.SuperbRank),
    RTLocation("Karate Man PERFECT", Regions.l0, "0_p", LocationType.PerfectRank),
    RTLocation("Karate Man 2 OK", Regions.l1, "1_o", LocationType.OkRank),
    RTLocation("Karate Man 2 SUPERB", Regions.l1, "1_s", LocationType.SuperbRank),
    RTLocation("Karate Man 2 PERFECT", Regions.l1, "1_p", LocationType.PerfectRank),
    RTLocation("Clappy Trio OK", Regions.l2, "2_o", LocationType.OkRank),
    RTLocation("Clappy Trio SUPERB", Regions.l2, "2_s", LocationType.SuperbRank),
    RTLocation("Clappy Trio PERFECT", Regions.l2, "2_p", LocationType.PerfectRank),
    RTLocation("Snappy Trio OK", Regions.l3, "3_o", LocationType.OkRank),
    RTLocation("Snappy Trio SUPERB", Regions.l3, "3_s", LocationType.SuperbRank),
    RTLocation("Snappy Trio PERFECT", Regions.l3, "3_p", LocationType.PerfectRank),
    RTLocation("Polyrhythm OK", Regions.l4, "4_o", LocationType.OkRank),
    RTLocation("Polyrhythm SUPERB", Regions.l4, "4_s", LocationType.SuperbRank),
    RTLocation("Polyrhythm PERFECT", Regions.l4, "4_p", LocationType.PerfectRank),
    RTLocation("Polyrhythm 2 OK", Regions.l5, "5_o", LocationType.OkRank),
    RTLocation("Polyrhythm 2 SUPERB", Regions.l5, "5_s", LocationType.SuperbRank),
    RTLocation("Polyrhythm 2 PERFECT", Regions.l5, "5_p", LocationType.PerfectRank),
    RTLocation("Night Walk OK", Regions.l6, "6_o", LocationType.OkRank),
    RTLocation("Night Walk SUPERB", Regions.l6, "6_s", LocationType.SuperbRank),
    RTLocation("Night Walk PERFECT", Regions.l6, "6_p", LocationType.PerfectRank),
    RTLocation("Night Walk 2 OK", Regions.l7, "7_o", LocationType.OkRank),
    RTLocation("Night Walk 2 SUPERB", Regions.l7, "7_s", LocationType.SuperbRank),
    RTLocation("Night Walk 2 PERFECT", Regions.l7, "7_p", LocationType.PerfectRank),
    RTLocation("Rhythm Tweezers OK", Regions.l8, "8_o", LocationType.OkRank),
    RTLocation("Rhythm Tweezers SUPERB", Regions.l8, "8_s", LocationType.SuperbRank),
    RTLocation("Rhythm Tweezers PERFECT", Regions.l8, "8_p", LocationType.PerfectRank),
    RTLocation("Rhythm Tweezers 2 OK", Regions.l9, "9_o", LocationType.OkRank),
    RTLocation("Rhythm Tweezers 2 SUPERB", Regions.l9, "9_s", LocationType.SuperbRank),
    RTLocation("Rhythm Tweezers 2 PERFECT", Regions.l9, "9_p", LocationType.PerfectRank),
    RTLocation("Sick Beats OK", Regions.l10, "10_o", LocationType.OkRank),
    RTLocation("Sick Beats SUPERB", Regions.l10, "10_s", LocationType.SuperbRank),
    RTLocation("Sick Beats PERFECT", Regions.l10, "10_p", LocationType.PerfectRank),
    RTLocation("Bouncy Road OK", Regions.l11, "11_o", LocationType.OkRank),
    RTLocation("Bouncy Road SUPERB", Regions.l11, "11_s", LocationType.SuperbRank),
    RTLocation("Bouncy Road PERFECT", Regions.l11, "11_p", LocationType.PerfectRank),
    RTLocation("Bouncy Road 2 OK", Regions.l12, "12_o", LocationType.OkRank),
    RTLocation("Bouncy Road 2 SUPERB", Regions.l12, "12_s", LocationType.SuperbRank),
    RTLocation("Bouncy Road 2 PERFECT", Regions.l12, "12_p", LocationType.PerfectRank),
    RTLocation("Ninja Bodyguard OK", Regions.l13, "13_o", LocationType.OkRank),
    RTLocation("Ninja Bodyguard SUPERB", Regions.l13, "13_s", LocationType.SuperbRank),
    RTLocation("Ninja Bodyguard PERFECT", Regions.l13, "13_p", LocationType.PerfectRank),
    RTLocation("Ninja Reincarnate OK", Regions.l14, "14_o", LocationType.OkRank),
    RTLocation("Ninja Reincarnate SUPERB", Regions.l14, "14_s", LocationType.SuperbRank),
    RTLocation("Ninja Reincarnate PERFECT", Regions.l14, "14_p", LocationType.PerfectRank),
    RTLocation("Sneaky Spirits OK", Regions.l15, "15_o", LocationType.OkRank),
    RTLocation("Sneaky Spirits SUPERB", Regions.l15, "15_s", LocationType.SuperbRank),
    RTLocation("Sneaky Spirits PERFECT", Regions.l15, "15_p", LocationType.PerfectRank),
    RTLocation("Sneaky Spirits 2 OK", Regions.l16, "16_o", LocationType.OkRank),
    RTLocation("Sneaky Spirits 2 SUPERB", Regions.l16, "16_s", LocationType.SuperbRank),
    RTLocation("Sneaky Spirits 2 PERFECT", Regions.l16, "16_p", LocationType.PerfectRank),
    RTLocation("Samurai Slice OK", Regions.l17, "17_o", LocationType.OkRank),
    RTLocation("Samurai Slice SUPERB", Regions.l17, "17_s", LocationType.SuperbRank),
    RTLocation("Samurai Slice PERFECT", Regions.l17, "17_p", LocationType.PerfectRank),
    RTLocation("Spaceball OK", Regions.l18, "18_o", LocationType.OkRank),
    RTLocation("Spaceball SUPERB", Regions.l18, "18_s", LocationType.SuperbRank),
    RTLocation("Spaceball PERFECT", Regions.l18, "18_p", LocationType.PerfectRank),
    RTLocation("Spaceball 2 OK", Regions.l19, "19_o", LocationType.OkRank),
    RTLocation("Spaceball 2 SUPERB", Regions.l19, "19_s", LocationType.SuperbRank),
    RTLocation("Spaceball 2 PERFECT", Regions.l19, "19_p", LocationType.PerfectRank),
    RTLocation("Tap Trial OK", Regions.l20, "20_o", LocationType.OkRank),
    RTLocation("Tap Trial SUPERB", Regions.l20, "20_s", LocationType.SuperbRank),
    RTLocation("Tap Trial PERFECT", Regions.l20, "20_p", LocationType.PerfectRank),
    RTLocation("Tap Trial 2 OK", Regions.l21, "21_o", LocationType.OkRank),
    RTLocation("Tap Trial 2 SUPERB", Regions.l21, "21_s", LocationType.SuperbRank),
    RTLocation("Tap Trial 2 PERFECT", Regions.l21, "21_p", LocationType.PerfectRank),
    RTLocation("Marching Orders OK", Regions.l22, "22_o", LocationType.OkRank),
    RTLocation("Marching Orders SUPERB", Regions.l22, "22_s", LocationType.SuperbRank),
    RTLocation("Marching Orders PERFECT", Regions.l22, "22_p", LocationType.PerfectRank),
    RTLocation("Marching Orders 2 OK", Regions.l23, "23_o", LocationType.OkRank),
    RTLocation("Marching Orders 2 SUPERB", Regions.l23, "23_s", LocationType.SuperbRank),
    RTLocation("Marching Orders 2 PERFECT", Regions.l23, "23_p", LocationType.PerfectRank),
    RTLocation("Wizards Waltz OK", Regions.l24, "24_o", LocationType.OkRank),
    RTLocation("Wizards Waltz SUPERB", Regions.l24, "24_s", LocationType.SuperbRank),
    RTLocation("Wizards Waltz PERFECT", Regions.l24, "24_p", LocationType.PerfectRank),
    RTLocation("Bunny Hop OK", Regions.l25, "25_o", LocationType.OkRank),
    RTLocation("Bunny Hop SUPERB", Regions.l25, "25_s", LocationType.SuperbRank),
    RTLocation("Bunny Hop PERFECT", Regions.l25, "25_p", LocationType.PerfectRank),
    RTLocation("Fireworks OK", Regions.l26, "26_o", LocationType.OkRank),
    RTLocation("Fireworks SUPERB", Regions.l26, "26_s", LocationType.SuperbRank),
    RTLocation("Fireworks PERFECT", Regions.l26, "26_p", LocationType.PerfectRank),
    RTLocation("Power Calligraphy OK", Regions.l27, "27_o", LocationType.OkRank),
    RTLocation("Power Calligraphy SUPERB", Regions.l27, "27_s", LocationType.SuperbRank),
    RTLocation("Power Calligraphy PERFECT", Regions.l27, "27_p", LocationType.PerfectRank),
    RTLocation("Toss Boys OK", Regions.l28, "28_o", LocationType.OkRank),
    RTLocation("Toss Boys SUPERB", Regions.l28, "28_s", LocationType.SuperbRank),
    RTLocation("Toss Boys PERFECT", Regions.l28, "28_p", LocationType.PerfectRank),
    RTLocation("Toss Boys 2 OK", Regions.l29, "29_o", LocationType.OkRank),
    RTLocation("Toss Boys 2 SUPERB", Regions.l29, "29_s", LocationType.SuperbRank),
    RTLocation("Toss Boys 2 PERFECT", Regions.l29, "29_p", LocationType.PerfectRank),
    RTLocation("Rat Race OK", Regions.l30, "30_o", LocationType.OkRank),
    RTLocation("Rat Race SUPERB", Regions.l30, "30_s", LocationType.SuperbRank),
    RTLocation("Rat Race PERFECT", Regions.l30, "30_p", LocationType.PerfectRank),
    RTLocation("Tram Pauline OK", Regions.l31, "31_o", LocationType.OkRank),
    RTLocation("Tram Pauline SUPERB", Regions.l31, "31_s", LocationType.SuperbRank),
    RTLocation("Tram Pauline PERFECT", Regions.l31, "31_p", LocationType.PerfectRank),
    RTLocation("Showtime OK", Regions.l32, "32_o", LocationType.OkRank),
    RTLocation("Showtime SUPERB", Regions.l32, "32_s", LocationType.SuperbRank),
    RTLocation("Showtime PERFECT", Regions.l32, "32_p", LocationType.PerfectRank),
    RTLocation("Space Dance OK", Regions.l33, "33_o", LocationType.OkRank),
    RTLocation("Space Dance SUPERB", Regions.l33, "33_s", LocationType.SuperbRank),
    RTLocation("Space Dance PERFECT", Regions.l33, "33_p", LocationType.PerfectRank),
    RTLocation("Cosmic Dance OK", Regions.l34, "34_o", LocationType.OkRank),
    RTLocation("Cosmic Dance SUPERB", Regions.l34, "34_s", LocationType.SuperbRank),
    RTLocation("Cosmic Dance PERFECT", Regions.l34, "34_p", LocationType.PerfectRank),
    RTLocation("Rap Men OK", Regions.l35, "35_o", LocationType.OkRank),
    RTLocation("Rap Men SUPERB", Regions.l35, "35_s", LocationType.SuperbRank),
    RTLocation("Rap Men PERFECT", Regions.l35, "35_p", LocationType.PerfectRank),
    RTLocation("Rap Women OK", Regions.l36, "36_o", LocationType.OkRank),
    RTLocation("Rap Women SUPERB", Regions.l36, "36_s", LocationType.SuperbRank),
    RTLocation("Rap Women PERFECT", Regions.l36, "36_p", LocationType.PerfectRank),
    RTLocation("Quiz Show OK", Regions.l37, "37_o", LocationType.OkRank),
    RTLocation("Quiz Show SUPERB", Regions.l37, "37_s", LocationType.SuperbRank),
    RTLocation("Quiz Show PERFECT", Regions.l37, "37_p", LocationType.PerfectRank),
    RTLocation("Bon Odori OK", Regions.l38, "38_o", LocationType.OkRank),
    RTLocation("Bon Odori SUPERB", Regions.l38, "38_s", LocationType.SuperbRank),
    RTLocation("Bon Odori PERFECT", Regions.l38, "38_p", LocationType.PerfectRank),
    RTLocation("Bon Dance OK", Regions.l39, "39_o", LocationType.OkRank),
    RTLocation("Bon Dance SUPERB", Regions.l39, "39_s", LocationType.SuperbRank),
    RTLocation("Bon Dance PERFECT", Regions.l39, "39_p", LocationType.PerfectRank),
    RTLocation("Remix 1 OK", Regions.l40, "40_o", LocationType.OkRank),
    RTLocation("Remix 1 SUPERB", Regions.l40, "40_s", LocationType.SuperbRank),
    RTLocation("Remix 1 PERFECT", Regions.l40, "40_p", LocationType.PerfectRank),
    RTLocation("Remix 2 OK", Regions.l41, "41_o", LocationType.OkRank),
    RTLocation("Remix 2 SUPERB", Regions.l41, "41_s", LocationType.SuperbRank),
    RTLocation("Remix 2 PERFECT", Regions.l41, "41_p", LocationType.PerfectRank),
    RTLocation("Remix 3 OK", Regions.l42, "42_o", LocationType.OkRank),
    RTLocation("Remix 3 SUPERB", Regions.l42, "42_s", LocationType.SuperbRank),
    RTLocation("Remix 3 PERFECT", Regions.l42, "42_p", LocationType.PerfectRank),
    RTLocation("Remix 4 OK", Regions.l43, "43_o", LocationType.OkRank),
    RTLocation("Remix 4 SUPERB", Regions.l43, "43_s", LocationType.SuperbRank),
    RTLocation("Remix 4 PERFECT", Regions.l43, "43_p", LocationType.PerfectRank),
    RTLocation("Remix 5 OK", Regions.l44, "44_o", LocationType.OkRank),
    RTLocation("Remix 5 SUPERB", Regions.l44, "44_s", LocationType.SuperbRank),
    RTLocation("Remix 5 PERFECT", Regions.l44, "44_p", LocationType.PerfectRank),
    RTLocation("Remix 6 OK", Regions.l45, "45_o", LocationType.OkRank),
    RTLocation("Remix 6 SUPERB", Regions.l45, "45_s", LocationType.SuperbRank),
    RTLocation("Remix 6 PERFECT", Regions.l45, "45_p", LocationType.PerfectRank),
    RTLocation("Remix 7 OK", Regions.l46, "46_o", LocationType.OkRank),
    RTLocation("Remix 7 SUPERB", Regions.l46, "46_s", LocationType.SuperbRank),
    RTLocation("Remix 7 PERFECT", Regions.l46, "46_p", LocationType.PerfectRank),
    RTLocation("Remix 8 OK", Regions.l47, "47_o", LocationType.OkRank),
    RTLocation("Remix 8 SUPERB", Regions.l47, "47_s", LocationType.SuperbRank),
    RTLocation("Remix 8 PERFECT", Regions.l47, "47_p", LocationType.PerfectRank)
]